### ISSUE TITLE
Upgrade to Numpy 1.9.2

### ISSUE THREAD

**Issue by cancan101** [deeplearningparis/dl-machine#5]
https://github.com/numpy/numpy/tree/v1.9.2

**Comment by cancan101** [comment]
Rather than git cloning numpy, you can just `pip install` it assuming the .numpy-site.cfg  file is in the right place: https://github.com/numpy/numpy/blob/98add1697398d93469889792739ca0721ac65284/site.cfg.example#L7-L8.

**Comment by ogrisel** [comment]
Indeed, please feel free to send a PR for this. scipy should probably be updated in the same way.
